name: docker-build-push-scan

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - 
        name: Setup Mondoo Client
        run: |
          curl -sSL https://mondoo.com/download.sh | bash
          ./mondoo version
          echo ${{ secrets.MONDOO_SERVICE_ACCOUNT }} | base64 -d > mondoo.json
          cat mondoo.json
          ./mondoo status --config mondoo.json

      - name: Build and push Docker images
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Print my docker imageid in a separate step
        run: echo "imageid ${{ steps.docker_build.outputs.imageid }}"

      # - name: Mondoo scan 
      #   run: ./mondoo scan docker docker://ghcr.io/${{ github.repository_owner }}/secure-python-app --config mondoo.json


      # -
      #   name: Login to GitHub Container Registry
      #   run: echo $GHCR_TOKEN | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      # - 
      #   name: Push image
      #   run: docker push ghcr.io/${{ github.repository_owner }}/secure-python-app